#The ID and name of every element
IdDict = {0:"empty", 1:"edge", 2:"messenger", 3:"monitor", 4:"player", 5:"ammo", 6:"torch", 7:"gem", 8:"key", 9:"door", 10:"scroll", 11:"passage", 12:"duplicator", 13:"bomb", 14:"energizer", 15:"star", 16:"clockwise", 17:"counter", 18:"bullet", 19:"water", 20:"forest", 21:"solid", 22:"normal", 23:"breakable", 24:"boulder", 25:"sliderns", 26:"sliderew", 27:"fake", 28:"invisible", 29:"blinkwall", 30:"transporter", 31:"line", 32:"ricochet", 33:"horizray", 34:"bear", 35:"ruffian", 36:"object", 37:"slime", 38:"shark", 39:"spinninggun", 40:"pusher", 41:"lion", 42:"tiger", 43:"vertray", 44:"head", 45:"segment", 46:"element46", 47:"bluetext", 48:"greentext", 49:"cyantext", 50:"redtext", 51:"purpletext", 52:"yellowtext", 53:"whitetext", 54:"bwhitetext", 55:"bbluetext", 56:"bgreentext", 57:"bcyantext", 58:"bredtext", 59:"bpurpletext", 60:"byellowtext", 61:"bgraytext", 62:"whitetext", 63:"bluetext", 64:"greentext", 65:"cyantext", 66:"redtext", 67:"purpletext", 68:"yellowtext", 69:"graytext"}
RevIDDict = {"empty":0, "edge":1, "messenger":2, "monitor":3, "player":4, "ammo":5, "torch":6, "gem":7, "key":8, "door":9, "scroll":10, "passage":11, "duplicator":12, "bomb":13, "energizer":14, "star":15, "clockwise":16, "counter":17, "bullet":18, "water":19, "forest":20, "solid":21, "normal":22, "breakable":23, "boulder":24, "sliderns":25, "sliderew":26, "fake":27, "invisible":28, "blinkwall":29, "transporter":30, "line":31, "ricochet":32, "horizray":33, "bear":34, "ruffian":35, "object":36, "slime":37, "shark":38, "spinninggun":39, "pusher":40, "lion":41, "tiger":42, "vertray":43, "head":44, "segment":45, "element46":46, "bluetext":47, "greentext":48, "cyantext":49, "redtext":50, "purpletext":51, "yellowtext":52, "whitetext":53, "bwhitetext":54, "bbluetext":55, "bgreentext":56, "bcyantext":57, "bredtext":58, "bpurpletext":59, "byellowtext":60, "bgraytext":61, "graytext":69}
RevColorDict = {"black":0, "darkblue":1, "darkgreen":2, "darkcyan":3, "darkred":4, "darkpurple":5, "darkyellow":6, "gray":7, "darkgray":8, "blue":9, "green":10, "cyan":11, "red":12, "purple":13, "yellow":14, "white":15}


#The default character of every element
CharDict = {0:32, 1:32, 2:63, 3:32, 4:2, 5:132, 6:157, 7:4, 8:12, 9:10, 10:232, 11:240, 12:250, 13:11, 14:127, 15:47, 16:47, 17:47, 18:248, 19:176, 20:176, 21:219, 22:178, 23:177, 24:254, 25:18, 26:29, 27:178, 28:32, 29:206, 30:62, 31:249, 32:42, 33:205, 34:153, 35:5, 36:2, 37:42, 38:94, 39:24, 40:16, 41:234, 42:227, 43:186, 44:233, 45:79, 46:63, 47:63, 48:63, 49:63, 50:63, 51:63, 52:63, 53:63, 54:63, 55:63, 56:63, 57:63, 58:63, 59:63, 60:63, 61:63, 62:63, 63:63, 64:63, 65:63, 66:63, 67:63, 68:63, 69:63}

#Proper background colors taken by text
AltTextDict = {47:"bgdarkblue", 48:"bgdarkgreen", 49:"bgdarkcyan", 50:"bgdarkred", 51:"bgdarkpurple", 52:"bgdarkyellow", 53:"bgblack", 54:"bgwhite", 55:"bgblue", 56:"bggreen", 57:"bgcyan", 58:"bgred", 59:"bgpurple", 60:"bgyellow", 61:"bgdarkgray", 62:"bgblack", 63:"bgdarkblue", 64:"bgdarkgreen", 65:"bgdarkcyan", 66:"bgdarkred", 67:"bgdarkpurple", 68:"bgdarkyellow", 69:"bggray"}
TextDict = {"bluetext":"bgdarkblue", "greentext":"bgdarkgreen", "cyantext":"bgdarkcyan", "redtext":"bgdarkred", "purpletext":"bgdarkpurple", "yellowtext":"bgdarkyellow", "whitetext":"bgblack", "bwhitetext":"bgdarkgray", "bbluetext":"bgblue", "bgreentext":"bggreen", "bcyantext":"bgcyan", "bredtext":"bgred", "bpurpletext":"bgpurple", "byellowtext":"bgyellow", "bgraytext":"bgwhite", "graytext":"bggray"}

#Color names to array numbers for graphics
ColorDict = {"blue":0, "green":1, "cyan":2, "red":3, "purple":4, "yellow":5, "white":6, "black":7, "darkblue":8, "darkgreen":9, "darkcyan":10, "darkred":11, "darkpurple":12, "darkyellow":13, "gray":14, "darkgray":15}
BGColorDict = {"bgblue":0, "bggreen":1, "bgcyan":2, "bgred":3, "bgpurple":4, "bgyellow":5, "bgwhite":6, "bgblack":7, "bgdarkblue":8, "bgdarkgreen":9, "bgdarkcyan":10, "bgdarkred":11, "bgdarkpurple":12, "bgdarkyellow":13, "bggray":14, "bgdarkgray":15}

#Tuples for line walls to determine which char the line wall should take
LineDict = {(0,0,0,0):249, (0,0,0,1):181, (0,0,1,0):198, (0,0,1,1):205, (0,1,0,0):210, (0,1,0,1):187, (0,1,1,0):201, (0,1,1,1):203, (1,0,0,0):208, (1,0,0,1):188, (1,0,1,0):200, (1,0,1,1):202, (1,1,0,0):186, (1,1,0,1):185, (1,1,1,0):204, (1,1,1,1):206}

#If the player tries to walk into element something happens.
#solid - Movement is stopped
#walkable - Movement is allowed
#interaction - Something is going to happen but I doubt it's implemented yet!
#DieItem - The element destroys itself and forces the player on top of it. Used for ammo/torch/gem
#InvisWall - You hit an invisible wall. What a dope.
#Push - Pushes the object if it can. Sliders and boulders.
CollisionDict = {"empty":"walkable", "edge":"ChangeBoard", "messenger":"solid", "monitor":"solid", "player":"solid", "ammo":"DieItem", "torch":"DieItem", "gem":"DieItem", "key":"DieItem", "door":"DieItem", "scroll":"Scroll", "passage":"Passage", "duplicator":"solid", "bomb":"Push", "energizer":"DieItem", "star":"interaction", "clockwise":"solid", "counter":"solid", "bullet":"DieItem", "water":"interaction", "forest":"DieItem", "solid":"solid", "normal":"solid", "breakable":"solid", "boulder":"Push", "sliderns":"Push", "sliderew":"Push", "fake":"walkable", "invisible":"InvisWall", "blinkwall":"solid", "transporter":"interaction", "line":"solid", "ricochet":"solid", "horizray":"solid", "bear":"DieItem", "ruffian":"DieItem", "object":"Touch", "slime":"slime", "shark":"interaction", "spinninggun":"solid", "pusher":"solid", "lion":"DieItem", "tiger":"DieItem", "vertray":"solid", "head":"DieItem", "segment":"DieItem", "element46":"solid", "bluetext":"solid", "greentext":"solid", "cyantext":"solid", "redtext":"solid", "purpletext":"solid", "yellowtext":"solid", "whitetext":"solid", "bwhitetext":"solid", "bbluetext":"solid", "bgreentext":"solid", "bcyantext":"solid", "bredtext":"solid", "bpurpletext":"solid", "byellowtext":"solid", "bgraytext":"solid", "graytext":"solid"}
#Same as above but for object behavior
ObjectDict = {"empty":"walkable", "edge":"solid", "messenger":"solid", "monitor":"solid", "player":"Push", "ammo":"Push", "torch":"solid", "gem":"Push", "key":"Push", "door":"solid", "scroll":"Push", "passage":"solid", "duplicator":"solid", "bomb":"Push", "energizer":"solid", "star":"solid", "clockwise":"solid", "counter":"solid", "bullet":"solid", "water":"solid", "forest":"solid", "solid":"solid", "normal":"solid", "breakable":"solid", "boulder":"Push", "sliderns":"Push", "sliderew":"Push", "fake":"walkable", "invisible":"solid", "blinkwall":"solid", "transporter":"solid", "line":"solid", "ricochet":"solid", "horizray":"solid", "bear":"Push", "ruffian":"Push", "object":"Push", "slime":"solid", "shark":"solid", "spinninggun":"solid", "pusher":"solid", "lion":"Push", "tiger":"Push", "vertray":"solid", "head":"solid", "segment":"solid", "element46":"solid", "bluetext":"solid", "greentext":"solid", "cyantext":"solid", "redtext":"solid", "purpletext":"solid", "yellowtext":"solid", "whitetext":"solid", "bwhitetext":"solid", "bbluetext":"solid", "bgreentext":"solid", "bcyantext":"solid", "bredtext":"solid", "bpurpletext":"solid", "byellowtext":"solid", "bgraytext":"solid", "graytext":"solid"}


#Noclip mode
NoClipDict = {"empty":"walkable", "edge":"solid", "messenger":"walkable", "monitor":"walkable", "player":"solid", "ammo":"DieItem", "torch":"DieItem", "gem":"DieItem", "key":"DieItem", "door":"walkable", "scroll":"interaction", "passage":"Passage", "duplicator":"walkable", "bomb":"walkable", "energizer":"DieItem", "star":"walkable", "clockwise":"walkable", "counter":"walkable", "bullet":"walkable", "water":"interaction", "forest":"DieItem", "solid":"walkable", "normal":"walkable", "breakable":"walkable", "boulder":"walkable", "sliderns":"walkable", "sliderew":"walkable", "fake":"walkable", "invisible":"walkable", "blinkwall":"walkable", "transporter":"interaction", "line":"walkable", "ricochet":"walkable", "horizray":"walkable", "bear":"walkable", "ruffian":"walkable", "object":"walkable", "slime":"interaction", "shark":"interaction", "spinninggun":"walkable", "pusher":"walkable", "lion":"walkable", "tiger":"walkable", "vertray":"walkable", "head":"walkable", "segment":"walkable", "element46":"walkable", "bluetext":"walkable", "greentext":"walkable", "cyantext":"walkable", "redtext":"walkable", "purpletext":"walkable", "yellowtext":"walkable", "whitetext":"walkable", "bwhitetext":"walkable", "bbluetext":"walkable", "bgreentext":"walkable", "bcyantext":"walkable", "bredtext":"walkable", "bpurpletext":"walkable", "byellowtext":"walkable", "bgraytext":"walkable", "graytext":"walkable"}
ClipDict = CollisionDict

#Key color to array position. Simple enough.
KeyDict = {"blue":0, "green":1, "cyan":2, "red":3, "purple":4, "yellow":5, "white":6, "black":7, "darkblue":0, "darkgreen":1, "darkcyan":2, "darkred":3, "darkpurple":4, "darkyellow":5, "gray":6, "darkgray":7}
KeyIndexDict = {0:"Blue", 1:"Green", 2:"Cyan", 3:"Red", 4:"Purple", 5:"Yellow", 6:"White", 7:"Black"}

#Door color to array position.
DoorDict = {"blue":0, "green":1, "cyan":2, "red":3, "purple":4, "yellow":5, "white":6, "black":7, "darkblue":0, "darkgreen":1, "darkcyan":2, "darkred":3, "darkpurple":4, "darkyellow":5, "gray":6, "darkgray":7}

#Bullet reactions
BulletDict = {"empty":"walkable", "edge":"solid", "messenger":"walkable", "monitor":"solid", "player":"hurt", "ammo":"solid", "torch":"solid", "gem":"solid", "key":"solid", "door":"solid", "scroll":"solid", "passage":"solid", "duplicator":"solid", "bomb":"solid", "energizer":"solid", "star":"solid", "clockwise":"solid", "counter":"solid", "bullet":"destroy", "water":"walkable", "forest":"solid", "solid":"solid", "normal":"solid", "breakable":"destroy", "boulder":"solid", "sliderns":"solid", "sliderew":"solid", "fake":"walkable", "invisible":"solid", "blinkwall":"solid", "transporter":"solid", "line":"solid", "ricochet":"ricochet", "horizray":"solid", "bear":"destroy", "ruffian":"destroy", "object":"Shot", "slime":"solid", "shark":"solid", "spinninggun":"solid", "pusher":"solid", "lion":"destroy", "tiger":"destroy", "vertray":"solid", "head":"destroy", "segment":"destroy", "element46":"solid", "bluetext":"solid", "greentext":"solid", "cyantext":"solid", "redtext":"solid", "purpletext":"solid", "yellowtext":"solid", "whitetext":"solid", "bwhitetext":"solid", "bbluetext":"solid", "bgreentext":"solid", "bcyantext":"solid", "bredtext":"solid", "bpurpletext":"solid", "byellowtext":"solid", "bgraytext":"solid", "graytext":"solid"}

"""ColorDict = {"9":blue, "a":green, "b":cyan, "c":red, "d":purple, "e":yellow, "f":white, "0":black, "1":darkblue, "2":darkgreen, "3":darkcyan, "4":darkred, "5":darkpurple, "6":darkyellow, "7":gray, "8":darkgray}
BGColorDict = {"9":bgblue, "a":bggreen, "b":bgcyan, "c":bgred, "d":bgpurple, "e":bgyellow, "f":bgwhite, "0":bgblack, "1":bgdarkblue, "2":bgdarkgreen, "3":bgdarkcyan, "4":bgdarkred, "5":bgdarkpurple, "6":bgdarkyellow, "7":bggray, "8":bgdarkgray}"""
#ThingsDict = {"empty":0, "edge":0, "messenger":0, "monitor":0, "player":player(input), "lion":0}

#Pushing
PushDict = {"empty":"go", "edge":"stop", "messenger":"stop", "monitor":"stop", "player":"push", "ammo":"push", "torch":"stop", "gem":"crush", "key":"push", "door":"stop", "scroll":"push", "passage":"stop", "duplicator":"stop", "bomb":"push", "energizer":"stop", "star":"stop", "clockwise":"stop", "counter":"stop", "bullet":"stop", "water":"stop", "forest":"stop", "solid":"stop", "normal":"stop", "breakable":"stop", "boulder":"push", "sliderns":"push", "sliderew":"push", "fake":"go", "invisible":"stop", "blinkwall":"stop", "transporter":"stop", "line":"stop", "ricochet":"stop", "horizray":"stop", "bear":"crush", "ruffian":"crush", "object":"stop", "slime":"stop", "shark":"stop", "spinninggun":"stop", "pusher":"stop", "lion":"crush", "tiger":"crush", "vertray":"stop", "head":"crush", "segment":"crush", "element46":"stop", "bluetext":"stop", "greentext":"stop", "cyantext":"stop", "redtext":"stop", "purpletext":"stop", "yellowtext":"stop", "whitetext":"stop", "bwhitetext":"stop", "bbluetext":"stop", "bgreentext":"stop", "bcyantext":"stop", "bredtext":"stop", "bpurpletext":"stop", "byellowtext":"stop", "bgraytext":"stop", "graytext":"stop"}

#Bombing
BombDict = {"empty":"boom", "edge":"no", "messenger":"no", "monitor":"no", "player":"hurt", "ammo":"no", "torch":"no", "gem":"boom", "key":"no", "door":"no", "scroll":"no", "passage":"no", "duplicator":"no", "bomb":"no", "energizer":"no", "star":"boom", "clockwise":"no", "counter":"no", "bullet":"boom", "water":"no", "forest":"no", "solid":"no", "normal":"no", "breakable":"boom", "boulder":"no", "sliderns":"no", "sliderew":"no", "fake":"no", "invisible":"no", "blinkwall":"no", "transporter":"no", "line":"no", "ricochet":"no", "horizray":"no", "bear":"boom", "ruffian":"boom", "object":"bombed", "slime":"no", "shark":"boom", "spinninggun":"no", "pusher":"no", "lion":"boom", "tiger":"boom", "vertray":"no", "head":"boom", "segment":"boom", "element46":"no", "bluetext":"no", "greentext":"no", "cyantext":"no", "redtext":"no", "purpletext":"no", "yellowtext":"no", "whitetext":"no", "bwhitetext":"no", "bbluetext":"no", "bgreentext":"no", "bcyantext":"no", "bredtext":"no", "bpurpletext":"no", "byellowtext":"no", "bgraytext":"no", "graytext":"no"}
#Bomb radius
BoomDict = {
(4,7):"Ignore", (4,6):"Ignore", (4,5):"Ignore", (4,4):"Boom", (4,3):"Boom", (4,2):"Boom", (4,1):"Boom", (4,0):"Boom", 
(3,7):"Ignore", (3,6):"Ignore", (3,5):"Boom", (3,4):"Boom", (3,3):"Boom", (3,2):"Boom", (3,1):"Boom", (3,0):"Boom", 
(2,7):"Ignore", (2,6):"Boom", (2,5):"Boom", (2,4):"Boom", (2,3):"Boom", (2,2):"Boom", (2,1):"Boom", (2,0):"Boom", 
(1,7):"Ignore", (1,6):"Boom", (1,5):"Boom", (1,4):"Boom", (1,3):"Boom", (1,2):"Boom", (1,1):"Boom", (1,0):"Boom",
(0,7):"Boom", (0,6):"Boom", (0,5):"Boom", (0,4):"Boom", (0,3):"Boom", (0,2):"Boom", (0,1):"Boom", (0,0):"Boom"}

#Torch Light
LightDict = {
(4,7):"Dark", (4,6):"Dark", (4,5):"Dark", (4,4):"Light", (4,3):"Light", (4,2):"Light", (4,1):"Light", (4,0):"Light", 
(3,7):"Dark", (3,6):"Dark", (3,5):"Light", (3,4):"Light", (3,3):"Light", (3,2):"Light", (3,1):"Light", (3,0):"Light", 
(2,7):"Dark", (2,6):"Light", (2,5):"Light", (2,4):"Light", (2,3):"Light", (2,2):"Light", (2,1):"Light", (2,0):"Light", 
(1,7):"Dark", (1,6):"Light", (1,5):"Light", (1,4):"Light", (1,3):"Light", (1,2):"Light", (1,1):"Light", (1,0):"Light",
(0,7):"Light", (0,6):"Light", (0,5):"Light", (0,4):"Light", (0,3):"Light", (0,2):"Light", (0,1):"Light", (0,0):"Light"}


#Movement ZZT-OOP related dictionaries
#Walking directions to x/y-steps
WalkDict = {"n":(0,-1), "s":(0,1), "e":(1,0), "w":(-1,0), "i":(0,0)}
#It's like WalkDict reversed!
FlowDict = {(0,-1):"n", (0,1):"s", (1,0):"e", (-1,0):"w", (0,0):"i"}
CwDict = {"n":"e", "s":"w", "e":"s", "w":"n", "i":"i"}
CcwDict = {"n":"w", "s":"e", "e":"n", "w":"s", "i":"i"}
OppDict = {"n":"s", "s":"n", "e":"w", "w":"e", "i":"i"}
RndpDict = {"n":["e", "w"], "s":["e", "w"], "e":["n", "s"], "w":["n", "s"], "i":["i"], "rndns":["e", "w"], "rndne":["n", "s", "e", "w"]}
IsDirDict = {"n":True, "s":True, "e":True, "w":True, "i":True, "seek":True, "flow":True}

#Bears have restrictions.
BearDict = {"empty":"walkable", "edge":"solid", "messenger":"solid", "monitor":"solid", "player":"hurt", "ammo":"solid", "torch":"solid", "gem":"solid", "key":"solid", "door":"solid", "scroll":"solid", "passage":"solid", "duplicator":"solid", "bomb":"solid", "energizer":"solid", "star":"solid", "clockwise":"solid", "counter":"solid", "bullet":"solid", "water":"solid", "forest":"solid", "solid":"solid", "normal":"solid", "breakable":"destroy", "boulder":"solid", "sliderns":"solid", "sliderew":"solid", "fake":"walkable", "invisible":"solid", "blinkwall":"solid", "transporter":"solid", "line":"solid", "ricochet":"solid", "horizray":"solid", "bear":"solid", "ruffian":"solid", "object":"solid", "slime":"solid", "shark":"solid", "spinninggun":"solid", "pusher":"solid", "lion":"solid", "tiger":"solid", "vertray":"solid", "head":"solid", "segment":"solid", "element46":"solid", "bluetext":"solid", "greentext":"solid", "cyantext":"solid", "redtext":"solid", "purpletext":"solid", "yellowtext":"solid", "whitetext":"solid", "bwhitetext":"solid", "bbluetext":"solid", "bgreentext":"solid", "bcyantext":"solid", "bredtext":"solid", "bpurpletext":"solid", "byellowtext":"solid", "bgraytext":"solid", "graytext":"solid"}

#Acceptable colors for #become
ValidColorDict = {"blue":"blue", "green":"green", "cyan":"cyan", "red":"red", "purple":"purple", "yellow":"yellow", "white":"white", "black":"black", "dblue":"dblue", "dgreen":"dgreen", "dcyan":"dcyan", "dred":"dred", "dpurple":"dpurple", "dyellow":"dyellow", "dwhite":"gray", "dblack":"dgray", "gray":"gray", "dgray":"dgray", "grey":"gray", "dgrey":"dgray", "any":"any", "def":"default"}
ValidElementDict = {"empty":True, "edge":True, "messenger":True, "monitor":True, "player":True, "ammo":True, "torch":True, "gem":True, "key":True, "door":True, "scroll":True, "passage":True, "duplicator":True, "bomb":True, "energizer":True, "star":True, "clockwise":True, "counter":True, "bullet":True, "water":True, "forest":True, "solid":True, "normal":True, "breakable":True, "boulder":True, "sliderns":True, "sliderew":True, "fake":True, "invisible":True, "blinkwall":True, "transporter":True, "line":True, "ricochet":True, "horizray":True, "bear":True, "ruffian":True, "object":True, "slime":True, "shark":True, "spinninggun":True, "pusher":True, "lion":True, "tiger":True, "vertray":True, "head":True, "segment":True, "element46":True, "bluetext":True, "greentext":True, "cyantext":True, "redtext":True, "purpletext":True, "yellowtext":True, "whitetext":True, "bwhitetext":True, "bbluetext":True, "bgreentext":True, "bcyantext":True, "bredtext":True, "bpurpletext":True, "byellowtext":True, "bgraytext":True, "graytext":True}

#Element names to Element IDs
Name2IdDict = {"empty":0, "edge":1, "messenger":2, "monitor":3, "player":4, "ammo":5, "torch":6, "gem":7, "key":8, "door":9, "scroll":10, "passage":11, "duplicator":12, "bomb":13, "energizer":14, "star":15, "clockwise":16, "counter":17, "bullet":18, "water":19, "forest":20, "solid":21, "normal":22, "breakable":23, "boulder":24, "sliderns":25, "sliderew":26, "fake":27, "invisible":28, "blinkwall":29, "transporter":30, "line":31, "ricochet":32, "horizray":33, "bear":34, "ruffian":35, "object":36, "slime":37, "shark":38, "spinninggun":39, "pusher":40, "lion":41, "tiger":42, "vertray":43, "head":44, "segment":45, "element46":46, "bluetext":47, "greentext":48, "cyantext":49, "redtext":50, "purpletext":51, "yellowtext":52, "whitetext":53, "bwhitetext":54, "bbluetext":55, "bgreentext":56, "bcyantext":57, "bredtext":58, "bpurpletext":59, "byellowtext":60, "bgraytext":61, "graytext":69}

#Default cycles for #becoming something with stats
StatDict = {"monitor":1, "player":1, "scroll":1, "duplicator":2, "bullet":1, "blinkwall":1, "object":3, "slime":3, "pusher":4, "tiger":2, "bomb":6, "bear":3, "ruffian":1, "shark":3, "head":2, "segment":2, "star":1, "transporter":2, "spinninggun":2, "lion":2}

#Conveyor Behavior (Go, Stop, Next)
ConveyDict = {"empty":"go", "edge":"stop", "messenger":"stop", "monitor":"stop", "player":"next", "ammo":"next", "torch":"stop", "gem":"next", "key":"next", "door":"stop", "scroll":"next", "passage":"stop", "duplicator":"stop", "bomb":"next", "energizer":"stop", "star":"stop", "clockwise":"stop", "counter":"stop", "bullet":"stop", "water":"stop", "forest":"stop", "solid":"stop", "normal":"stop", "breakable":"stop", "boulder":"next", "sliderns":"stop", "sliderew":"stop", "fake":"stop", "invisible":"stop", "blinkwall":"stop", "transporter":"stop", "line":"stop", "ricochet":"stop", "horizray":"stop", "bear":"stop", "ruffian":"stop", "object":"stop", "slime":"stop", "shark":"stop", "spinninggun":"stop", "pusher":"stop", "lion":"stop", "tiger":"stop", "vertray":"stop", "head":"stop", "segment":"stop", "element46":"stop", "bluetext":"stop", "greentext":"stop", "cyantext":"stop", "redtext":"stop", "purpletext":"stop", "yellowtext":"stop", "whitetext":"stop", "bwhitetext":"stop", "bbluetext":"stop", "bgreentext":"stop", "bcyantext":"stop", "bredtext":"stop", "bpurpletext":"stop", "byellowtext":"stop", "bgraytext":"stop", "graytext":"stop"}
